### ISSUE TITLE
Does Artifact.Storage actually cache the result?

### ISSUE THREAD

**Issue by aphillipo** [doomspork/artifact#9]
Hi @doomspork !

Does Artifact.Storage actually work and are you caching the output - I'm seeing incredibly slow load times on my image - it seems to be processed every time maybe?

Happy to get on IRC at some point and discuss... Do you mind me opening questions like this here?

**Comment by doomspork** [comment]
Howdy @aphillipo!  I happy you're interested in this project, it's exciting.

Storage is used for storing the original unaltered image.  The transformed images _are not_ stored or cached.  Ideally you'd either use a CDN or some other form of caching in front of Artifact. 

Are you familiar with how [Dragonfly](https://github.com/markevans/dragonfly) works?  I've taken a similar approach.

I rarely sign on IRC these days but I'm almost always on Slack.  You can reach me on the Elixir Slack as `@seanc`.

**Comment by aphillipo** [comment]
Yes I have used DragonFly before but I found it a bit confusing - I come from a non ruby background but used it when I wrote a site in locomotivecms.  I think my lack of ruby was the confusing bit.

I have a feeling that artifact (nice name!) could end up performing very well compared to other solutions.  I could envisage eventually having all the artifact servers detect each other and other clever stuff.

I'm incredibly new to Elixir but I'm building a startup in it which is even more exciting!

**Comment by doomspork** [comment]
I would love to build in features to support distributed artifact servers!  The potential is limitless (or so it seems).

If you'd like to ping me on Slack I'd be glad to help example any of these topics that may be confusing :grinning:

**Comment by doomspork** [comment]
@aphillipo can we close this issue?

**Comment by doomspork** [comment]
Thank you :+1:
